###
#
# Browse Books
#
GET http://localhost:4004/browse/Books?
  # &$select=title,stock
  # &$expand=currency
  # &sap-language=de

###
#
# Get Book wit ID 201
#
GET http://localhost:4004/browse/Books(201)

###
#
# Update Author with ID 101
#
POST http://localhost:4004/odata/v4/admin/Authors
Content-Type: application/json

{"ID": 101, "name": "Some Author"}


###
#
# Order a Book
#
POST http://localhost:4004/browse/Orders
Content-Type: application/json;IEEE754Compatible=true

{"book_ID": 201, "amount": 5}


